version: '3.7'
services:
    minfi:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
            # set arguments from global .env file
            args:
                maintainer: $maintainer
        ports:
            - ${service_port}:8080
        networks:
            - minfi
        volumes:
            - ${dev_repo_dir}:/webapp # map local development directory to prevent having to rebuild image for changes
        # tag the image
        image: minfi/webapp:1.0
        container_name: min_fi_webapp
# connect to container network
networks:
    minfi:
        name: minfi